# => Register Oracle protection sources
---
  - hosts: localhost
    gather_facts: no
    become: False
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      # => Cycle through each member of the hosts and register as Cohesity Protection Source
      - name: Create new Protection Source as Oracle source.
        include_role:
            name: cohesity.cohesity_ansible_role
            tasks_from: oracle_source
        vars:
            cohesity_server: "{{ var_cohesity_server }}"
            cohesity_admin: "{{ var_cohesity_username }}"
            cohesity_password: "{{ var_cohesity_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_oracle:
                state: present
                force_register: True
                endpoint: "{{ item }}"
                db_username: "{{ db_username }}"
                db_password: "{{ db_password }}"
        with_items: "{{ groups['oracle'] }}"
