#=> Create a Oracle database restore(clone) to protection view.
---
  - hosts: localhost
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Restore Oracle Job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: oracle_restore
        vars:
          cohesity_server: "{{ var_cohesity_server }}"
          cohesity_admin: "{{ var_cohesity_username }}"
          cohesity_password: "{{ var_cohesity_password }}"
          cohesity_validate_certs: "{{ var_validate_certs }}"
          cohesity_oracle:
              source_db: cdb1
              task_name: recover_tasks
              clone_app_view: True
              source_server: {{ source_server }}
