# => Register Oracle protection sources
---
  - hosts: localhost
    gather_facts: no
    become: False
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      # => Cycle through each member of the hosts and register as Cohesity Protection Source
      - name: Create new Protection Source as Oracle source.
        include_role:
            name: cohesity.cohesity_ansible_role
            tasks_from: oracle_source
        vars:
            cohesity_server: orcl-serv2-eng-db.com
            cohesity_admin: "{{ var_cohesity_username }}"
            cohesity_password: "{{ cohesity_cluster_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_oracle:
                state: absent
                endpoint: "{{ item }}"
        with_items: "{{ groups['oracle'] }}"
