#!/bin/ansible-playbook
#
---
- hosts: all
  user: ansibleuser
  become: true
  vars:
    pkgs:
      - sssd
      - sssd-tools
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - adcli
      - samba-common
      - samba-common-tools
      - krb5-workstation
      - openldap-clients
    AD_Domain: LUC3.NET
    AD_Domain_alt: luc3.net
    Join_OU: OU="member servers",OU=computers,DC=luc3,DC=net
    SRV_ADM_GRP_OU: OU=groups,DC=luc3,DC=net
  vars_prompt:
    - name: username
      prompt: "What is your AD administrator username?"
      private: no
    - name: password
      prompt: "What is your AD administrator password?"
      private: yes
    - name: adhostname
      prompt: "What is the desired hostname in a simple, non-fqdn format?"
      private: no
  tasks:
  - name: Checking if running RedHat/CentOS
    fail:
      msg: The system is not running RedHat/CentOS, aborting
    when: ansible_facts['os_family'] != 'RedHat'
  - name: Checking if packages required to join AD realm are present
    yum: name={{ pkgs }} state=present update_cache=yes
  - name: Settings up hostname
    shell: hostnamectl set-hostname {{ adhostname }}.{{ AD_Domain_alt }}
  - name: Joinining the AD realm (creating AD computer account and updating /etc/krb5.keytab)
    shell: echo '{{ password }}' | adcli join --stdin-password {{ AD_Domain }} -U {{ username }} --domain-ou={{ Join_OU }}
  - name: Creating AD server admin group
    shell: echo '{{ password }}' | adcli create-group ADM_{{ adhostname }} --stdin-password --domain={{ AD_Domain }} --description="Admin group for {{ adhostname }} server" --domain-ou={{ SRV_ADM_GRP_OU }} -U {{ username }}
  - name: Configuring sssd.conf
    template:
      src: sssd.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600
  - name: Configuring krb5.conf
    template:
      src: krb5.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644
  - name: Configuring sudoers
    template:
      src: ADsudoers.j2
      dest: /etc/sudoers.d/ADsudoers
      owner: root
      group: root
      mode: 0440
  - name: Configuring PAM/SSHD to use SSSD
    shell: authselect select sssd with-mkhomedir --force
  - name: Enabling oddjobd service
    systemd:
      name: oddjobd.service
      enabled: yes
      state: started
  - name: Restarting SSSD
    systemd:
      name: sssd
      enabled: yes
      state: restarted