---
- name: "Cohesity Protection Source: Set {{ cohesity_oracle.endpoint | default('endpoint') }} to state of {{ cohesity_oracle.state | default('present') }}"
  cohesity_oracle_source:
    cluster: "{{ cohesity_server }}"
    username: "{{ cohesity_admin }}"
    password: "{{ cohesity_password }}"
    validate_certs: "{{ cohesity_validate_certs | default(False) }}"
    force_register: "{{ cohesity_oracle.force_register | default(False) }}"
    state: "{{ cohesity_oracle.state | default('present') }}"
    endpoint: "{{ cohesity_oracle.endpoint | default('') }}"
    db_username: "{{ cohesity_oracle.db_username | default('') }}"
    db_password: "{{ cohesity_oracle.db_password | default('') }}"
  tags: always