---
- name: "Cohesity Restore tasks: Restore {{ cohesity_oracle.source_server }} to server/view"
  cohesity_oracle_restore:
    cluster: "{{ cohesity_server }}"
    username: "{{ cohesity_admin }}"
    password: "{{ cohesity_password }}"
    validate_certs: "{{ cohesity_validate_certs | default(False) }}"
    task_name: "{{ cohesity_oracle.task_name | default('')}}"
    clone_app_view: "{{ cohesity_oracle.clone_app_view | default(False)}}"
    source_db: "{{ cohesity_oracle.source_db}}"
    source_server: "{{ cohesity_oracle.source_server }}"
    target_server: "{{ cohesity_oracle.target_server | default('') }}"
    target_db: "{{ cohesity_oracle.target_db | default('') }}"
    oracle_home: "{{ cohesity_oracle.oracle_home | default('') }}"
    oracle_base: "{{ cohesity_oracle.oracle_base | default('') }}"
    oracle_data: "{{ cohesity_oracle.oracle_data | default('') }}"
    channels: "{{ cohesity_oracle.channels | default('') }}"
    control_file: "{{ cohesity_oracle.control_file | default('') }}"
    redo_log_path: "{{ cohesity_oracle.redo_log_path | default('') }}"
    audit_path: "{{ cohesity_oracle.audit_path | default('') }}"
    diag_path: "{{ cohesity_oracle.diag_path | default('') }}"
    fra_path: "{{ cohesity_oracle.fra_path | default('') }}"
    fra_size_mb: "{{ cohesity_oracle.frs_size_mb | default(2048) }}"
    bct_file: "{{ cohesity_oracle.bct_file | default('') }}"
    log_time: "{{ cohesity_oracle.log_time | default('') }}"
    overwrite: "{{ cohesity_oracle.overwrite | default(False) }}"
    no_recovery: "{{ cohesity_oracle.no_recovery | default(False) }}"
  tags: always
