#!/bin/ansible-playbook
########################

# DESCRIPTION
# Creates and Removes Client Device Alias on Cisco MDS

# DIRECTIONS
# Usage to create a single device-alias
# Run ./create-device-alias.yml --tags create-adhoc -e "alias_name=esx-server01,wwpn=56:2:22:11:22:88:11:67" -v

# Usage to remove a single device-alias (note, wwpn value not required to remove)
# Run ./create-device-alias.yml --tags remove-adhoc -e "alias_name=esx-server01" -v

# Usage to create multiple device-alias using device-alias.csv file: 
#     1. create a file called device-alias.csv in the same directory as this playbook.
#     2. Make 3 columns titled "Hostname", "WWPNA", and "WWPNB"
#     3. fill in the values in all columns for all the hosts you want to create.
#
# Run ./create-device-alias.yml --tags create-csv -v

# Usage to remove multiple device-alias using device-alias.csv file:
# Run ./create-device-alias.yml --tags remove-csv -v

---
- name: "##### Creates and Removes Client Device Alias on Cisco MDS #####"
  gather_facts: no
  hosts: '{{target|default("cisco-mds")}}'
  vars:
    creds:
      host: "{{ inventory_hostname }}"
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli
  tasks:

    - name: Reading the csv file
      read_csv:
        path: device-alias.csv
      register: alias_list
      delegate_to: localhost      
      tags:
      - create-csv
      - remove-csv    
      
    - name: Creates Cisco MDS device-alias from device-alias.csv
      nxos_devicealias:
          distribute: yes
          mode: enhanced
          da:
              - { name: '{{ item.Hostname }}_HB{{ fabricid }}', pwwn: '{{ item.WWPN{{ fabricid }} }}'}
             # - { name: '{{ item.Hostname }}_HB{{ fabricid }}', remove: True}
          provider: "{{ creds }}"          
      loop: "{{ alias_list.list }}"
      register: result
      tags:
      - create-csv
    - debug: var=result

    - name: Removes Cisco MDS device alias from device-alias.csv
      nxos_devicealias:
          distribute: yes
          mode: enhanced
          da:
             # - { name: '{{ item.Hostname }}_HB{{ fabricid }}', pwwn: '{{ item.WWPN{{ fabricid }} }}'}
              - { name: '{{ item.Hostname }}_HB{{ fabricid }}', remove: True}
          provider: "{{ creds }}"          
      loop: "{{ alias_list.list }}"
      register: result
      tags:
      - remove-csv
    - debug: var=result

    - name: Creates Cisco MDS device alias
      nxos_devicealias:
          distribute: yes
          mode: enhanced
          da:
              - { name: '{{ alias_name }}', pwwn: '{{ wwpn }}'}
             # - { name: '{{ alias_name }}', remove: True}
          provider: "{{ creds }}"          
      loop: "{{ alias_list.list }}"
      register: result
      tags:
      - create-adhoc
    - debug: var=result 

    - name: Removes Cisco MDS device alias
      nxos_devicealias:
          distribute: yes
          mode: enhanced
          da:
             # - { name: '{{ alias_name }}', pwwn: '{{ wwpn }}'}
              - { name: '{{ alias_name }}', remove: True}
          provider: "{{ creds }}"          
      loop: "{{ alias_list.list }}"
      register: result
      tags:
      - remove-adhoc
    - debug: var=result  