#!/bin/ansible-playbook
########################

# DESCRIPTION
# Creates and Removes Zones on Cisco MDS

# DIRECTIONS
# Usage to create multiple fabric zones using A_zones.csv or B_zones.csv file: 
#     1. create a file called A_zones.csv and B_zones.csv in the same directory as this playbook.
#     2. Make 4 columns titled "Host_Alias_Name", "Arrayname", "Array_Alias_CT0", "Array_Alias_CT1"
#         a. "Host_Alias_Name" is the alias of the host initiator.
#         b. "Arrayname" is the short name for the storage array, not the individual controller names.  Does not need to correspond to an alias.
#         c. "Array_Alias_CT0" and "Array_Alias_CT1" respectively are the alias names on each controller (CT0=Controller 0, CT1=Controller 1.  Some array manufactures call these "SP" for storage processors or "SC" for storage controller ) for the ports you want to make the targets.  In a highly available setup you should have one port on each controller per zone. This depends upon your cabling strategy, in general I recommend a simple strategy where even FC ports connect to fabric A and odd FC ports connect to fabric B.
#     3. fill in the values in all columns for all the hosts you want to create.
#     4. Note: Your switches should have defined vars for "vsanid" and "fabricid".

# Run ./create-zones.yml --tags create-csv -v

# Usage to remove multiple zones using A_zones.csv or B_zones.csv file:
# Run ./create-zones.yml --tags remove-csv -v

---

- name: "##### Creates zones and adds to zoneset on Cisco MDS #####"
  gather_facts: no
  hosts: '{{target|default("cisco_mds")}}'
  vars:
    creds:
      host: "{{ inventory_hostname }}"
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli #nxapi

  tasks:

    - name: Reading the A_zones.csv file
      read_csv:
        path: A_zones.csv
      register: A_zones_list
      delegate_to: localhost
      when: fabricid == "A"    
      tags:
      - create-csv
      - remove-csv

    - name: Reading the B_zones.csv file
      read_csv:
        path: B_zones.csv
      register: B_zones_list
      delegate_to: localhost
      when: fabricid == "B"    
      tags:
      - create-csv
      - remove-csv  

    - name: Create zones from csv file
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zone:
          - members:
            - devtype: initiator
              device_alias: "{{ item.Host_Alias_Name }}"
            - devtype: target
              device_alias: "{{ item.Array_Alias_CT0 }}"
            - devtype: target
              device_alias: "{{ item.Array_Alias_CT1 }}"
            name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
            remove: no
      when: fabricid == "A"
      loop: "{{ A_zones_list.list }}"
      tags:
      - create-csv

    - name: Add zones to active zoneset
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zoneset:
          - action: activate
            members:
            - name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
            name: "{{ zs_name }}"
            remove: no
      when: fabricid == "A"
      loop: "{{ A_zones_list.list }}"
      tags:
      - create-csv

    - name: Create zones from csv file
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zone:
          - members:
            - devtype: initiator
              device_alias: "{{ item.Host_Alias_Name }}"
            - devtype: target
              device_alias: "{{ item.Array_Alias_CT0 }}"
            - devtype: target
              device_alias: "{{ item.Array_Alias_CT1 }}"
            name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
            remove: no
      when: fabricid == "B"
      loop: "{{ B_zones_list.list }}"
      tags:
      - create-csv

    - name: Add zones to active zoneset
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zoneset:
          - action: activate
            members:
            - name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
            name: "{{ zs_name }}"
            remove: no
      when: fabricid == "B"
      loop: "{{ B_zones_list.list }}"
      tags:
      - create-csv

    - name: Removes zones from the active zoneset
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zoneset:
          - action: activate
            members:
            - name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
              remove: True            
            name: "{{ zs_name }}"
            remove: no
      when: fabricid == "A"
      loop: "{{ A_zones_list.list }}"
      tags:
      - remove-csv

    - name: Deletes zones found in zones.csv file
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zone:
          - members:
            - device_alias: "{{ item.Host_Alias_Name }}"
            - device_alias: "{{ item.Array_Alias_CT0 }}"
            - device_alias: "{{ item.Array_Alias_CT1 }}"
              remove: True
            name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
            remove: True
      when: fabricid == "A"
      loop: "{{ A_zones_list.list }}"
      tags:
      - remove-csv

    - name: Removes zones from the active zoneset
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zoneset:
          - action: activate
            members:
            - name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
              remove: True            
            name: "{{ zs_name }}"
            remove: no
      when: fabricid == "B"
      loop: "{{ B_zones_list.list }}"
      tags:
      - remove-csv

    - name: Deletes zones found in zones.csv file
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
        - vsan: "{{ vsanid }}"
          mode: enhanced
          smart_zoning: yes
          zone:
          - members:
            - device_alias: "{{ item.Host_Alias_Name }}"
            - device_alias: "{{ item.Array_Alias_CT0 }}"
            - device_alias: "{{ item.Array_Alias_CT1 }}"
              remove: True
            name: '{{ item.Host_Alias_Name }}_{{ item.Arrayname }}'
            remove: True
      when: fabricid == "B"
      loop: "{{ B_zones_list.list }}"
      tags:
      - remove-csv
