#!/bin/ansible-playbook
########################

# DESCRIPTION
# Creates and Removes Zones on Cisco MDS

# DIRECTIONS
# Usage to create multiple fabric zones using A_zones.csv or B_zones.csv file: 
#     1. create a file called A_zones.csv and B_zones.csv in the same directory as this playbook.
#     2. Make 3 columns titled "Hostname", "Arrayname", "Array-CT0", "Array-CT1"
#     3. fill in the values in all columns for all the hosts you want to create.
#     4. Note: Your switches should have defined vars for "vsanid" and "fabricid".

# Run ./create-zones.yml --tags create-csv -v

# Usage to remove multiple zones using A_zones.csv or B_zones.csv file:
# Run ./create-zones.yml --tags remove-csv -v

---

- name: "##### Creates zones and adds to zoneset on Cisco MDS #####"
  gather_facts: no
  hosts: '{{target|default("cisco-mds")}}'
  vars:
    creds:
      host: "{{ inventory_hostname }}"
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: cli #nxapi

  tasks:

    - name: Reading the csv file
      read_csv:
        path: "{{ fabricid }}_zones.csv"
      register: "{{ fabricid }}_zones_list"
      delegate_to: localhost      
      tags:
      - create-csv
      - remove-csv

    - name: Ensure the required vsans exist
      cisco.nxos.nxos_vsan:
        vsan:
        - id: "{{ vsanid }}"
          name: "{{ vsan_name }}"
          remove: false
          suspend: false
        provider: "{{ creds }}"
      tags:
      - create-csv

    - name: Create zones from csv file and add zones to active zoneset
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
           - vsan: "{{ vsanid }}"
             mode: enhanced
             smart_zoning: yes
             zone:
                - name: '{{ item.Hostname }}-HB{{ fabricid }}_{{ item.Arrayname }}'
                  members:
                     - devtype: initiator
                     - device-alias: "{{ item.Hostname }}"
                     - devtype: target
                     - device-alias: "{{ item.Array-CT0 }}"
                     - device-alias: "{{ item.Array-CT1 }}"
                    #  - {pwwn: '61:61:62:62:12:12:12:12', remove: True}
                # - name: zoneB
                #   members:
                #      - {pwwn: '10:11:11:11:11:11:11:11'}
                #      - {pwwn: '62:62:62:62:21:21:21:21'}
                # - name: zoneC
                #   remove: True
             zoneset:
                 - name: zs_vsan{{ vsanid }}
                   members:
                      - {name: '{{ item.Hostname }}-HB{{ fabricid }}_{{ item.Arrayname }}'}
                      # - {name: zoneB}
                      # - {name: zoneC, remove: True}
                   action: activate
      loop: "{{ {{ fabricid }}_zones_list.list }}"
      tags:
      - create-csv
      register: result
    - debug: var=result

    - name: Removes zones from the zoneset and deletes zones found in zones.csv file
      cisco.nxos.nxos_zone_zoneset:
        provider: "{{ creds }}"
        zone_zoneset_details:
          - vsan: "{{ vsanid }}"
            mode: enhanced
            smart_zoning: yes
            zoneset:
              - name: zs_vsan{{ vsanid }}
                members:
                  - {name: '{{ item.Hostname }}-HB{{ fabricid }}_{{ item.Arrayname }}', remove: True}
                      # - {name: zoneB}
                      # - {name: zoneC, remove: True}
                action: activate
            zone:
              - name: '{{ item.Hostname }}-HB{{ fabricid }}_{{ item.Arrayname }}'
                members:
                  - devtype: initiator
                  - device-alias: "{{ item.Hostname }}", remove: True}
                  - devtype: target
                  - device-alias: "{{ item.Array-CT0 }}", remove: True}
                  - device-alias: "{{ item.Array-CT1 }}", remove: True}
                    #  - {pwwn: '61:61:62:62:12:12:12:12', remove: True}
                # - name: zoneB
                #   members:
                #      - {pwwn: '10:11:11:11:11:11:11:11'}
                #      - {pwwn: '62:62:62:62:21:21:21:21'}
                - name: '{{ item.Hostname }}-HB{{ fabricid }}_{{ item.Arrayname }}'
                  remove: True

      loop: "{{ {{ fabricid }}_zones_list.list }}"
      tags:
      - remove-csv
      register: result
    - debug: var=result