#!/bin/ansible-playbook
---
- name: "##### Create a new LUN volume on FlashArrays #####"
  hosts: '{{target|default("purefa")}}'
  gather_facts: False

  vars_prompt:
    - name: volume
      prompt: "Enter the volume label. (example: ansible-vol01):"
      private: no
    - name: size
      prompt: "Enter the volume capacity. (example: 1T):"
      private: no

  tasks:
    - name: Create new LUN volume on FlashArray
      delegate_to: localhost
      purestorage.flasharray.purefa_volume:
        fa_url: "{{ fa_url }}"
        api_token: "{{ fa_token }}"
        name: "{{ volume }}"
        size: "{{ size }}"
        state: present