#!/bin/ansible-playbook
########################
# Usage: 
#         1. create a file called hosts.csv in the same directory as this playbook.
#         2. Make 4 columns titled "Hostname", "Platform", "WWPNA", and "WWPNB"
#         3. fill in the values in all columns for all the hosts you want to create.
#         4. Run the playbook: ansible-playbook create-host-volume.yaml --limit PSFAX01-01ARU13 -v
# 
---
- name: "##### Create hosts on FlashArrays #####"
  hosts: '{{target|default("purefa")}}'
  gather_facts: False

  tasks:

    - name: Reading the csv file
      read_csv:
        path: hosts.csv
      register: hosts_list
      delegate_to: localhost

    - name: Creates hosts from CSV file on FlashArrays
      delegate_to: localhost
      purestorage.flasharray.purefa_host:
        name: "{{ item.Hostname }}"
        personality: "{{ item.Platform }}"       
        wwns:
        - "{{ item.WWPNA }}"
        - "{{ item.WWPNB }}"
        fa_url: "{{ fa_url }}"
        api_token: "{{ fa_token }}"
      loop: "{{ hosts_list.list }}" 