#!/bin/ansible-playbook
---
- name: "##### Sets new FlashArray login banner #####"
  hosts: '{{target|default("purefa")}}'
  gather_facts: False

  tasks:
      # Set login banner on FlashArrays
    - name: Delete banner text
      delegate_to: localhost
      purestorage.flasharray.purefa_banner:
        state: absent
        fa_url: "{{ fa_url }}"
        api_token: "{{ fa_api }}"

    - name: Set new banner text
      delegate_to: localhost
      purestorage.flasharray.purefa_banner:
        banner: "{{ banner_text }}"
        state: present
        fa_url: "{{ fa_url }}"
        api_token: "{{ fa_api }}"

