#!/bin/ansible-playbook
---
- name: "##### Configure SMTP settings on FlashBlade #####"
  hosts: '{{target|default("purefb")}}'
  gather_facts: False

  tasks:
    # Set SMTP email server and alert mail address
    - name: Set SMTP settings
      delegate_to: localhost
      purestorage.flashblade.purefb_smtp:
        host: "{{ smtp_server }}"
        domain: "{{ domain_name }}"
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_token }}"

    - name: Delete existing email recipient
      delegate_to: localhost
      purestorage.flashblade.purefb_alert:
        state: absent
        address: "{{ recipient_email }}"
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_token }}"


    - name: Add new email recipient and enable, or enable existing email
      delegate_to: localhost
      purestorage.flashblade.purefb_alert:
        address: "{{ recipient_email }}"
        enabled: true
        state: present
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_token }}"
