#!/bin/ansible-playbook
---
- hosts: localhost
  gather_facts: True
  become: True
  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"
  tasks:
  - name: Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    when: ansible_os_family == "RedHat"
 
  - name: Import EPEL GPG key.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: ansible_os_family == "RedHat"
 
  - name: Install python-pip module on RedHat
    yum:
      name: python3-pip
    when: ansible_os_family == "RedHat"
 
  - name: Install python-pip module on Ubuntu
    apt:
      name: python-pip
    when: ansible_os_family == "Debian"
 
  - name: Install python-pip module on SuSE
    zypper:
      name: python-pip
    when: ansible_os_family == "Suse"
 
  - name: Install Pure Storage & Cohesity SDKs
    pip:
      name: ['purestorage', 'purity_fb', 'cohesity-management-sdk', 'storops', 'pexpect', 'pywinrm', 'py-pure-client', 'hvac', 'python-ecsclient', 'py-zabbix']

  - name: Install Galaxy Collections
    shell: ansible-galaxy collection install purestorage.flasharray; ansible-galaxy collection install purestorage.flashblade; ansible-galaxy role install cohesity.cohesity_ansible_role; ansible-galaxy collection install dellemc.unity; ansible-galaxy collection install cisco.nxos; ansible-galaxy collection install community.hashi_vault
    args:
      executable: /bin/bash