#!/bin/ansible-playbook
---
- name: Join RHEL to Luc3.net Playbook
  hosts: ubuntu
  user: sysadmin
  become: true
  become_user: root
  vars:
    ad_domain_name: LUC3.NET
    ad_domain_name_alt: luc3.net
    ou_location: OU="linux servers",DC=luc3,DC=net
    srv_adm_grp_ou: OU=groups,DC=luc3,DC=net
    provider: ad

  vars_prompt:
    - name: username
      prompt: "What is your AD administrator username?"
      private: no
    - name: password
      prompt: "What is your AD administrator password?"
      private: yes
    - name: adhostname
      prompt: "What is the desired hostname in a simple, non-fqdn format?"
      private: no

  tasks:
    - name: Install required packages to join RHEL to Active Directory domain
      yum:
        name:
          - sssd
          - sssd-tools
          - realmd
          - oddjob
          - oddjob-mkhomedir
          - adcli
          - samba-common
          - samba-common-tools
          - krb5-workstation
          - openldap-clients
          - python3-policycoreutils
          - bind-utils
          - authselect-compat
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install required packages to join Ubuntu to Active Directory domain
      apt:
        name:
          - sssd
          - sssd-ad
          - sssd-tools
          - realmd
          - oddjob
          - oddjob-mkhomedir
          - adcli
          - krb5-user
          - sssd-krb5
          - samba-common
          - smbldap-tools
          - smbclient
        state: present
      when: ansible_os_family == "Debian"

    - name: Settings up hostname
      shell: hostnamectl set-hostname {{ adhostname }}.{{ ad_domain_name_alt }}

    - name: Grab a kerberos ticket for the AD Admin User
      shell: kinit {{ username }}

    - name: Joinining the AD realm (creating AD computer account and updating /etc/krb5.keytab)
      shell: echo '{{ password }}' | adcli join --stdin-password {{ ad_domain_name }} -U {{ username }} --domain-ou={{ ou_location }} --automatic-id-mapping=no
  
    - name: Creating AD server admin group
      shell: echo '{{ password }}' | adcli create-group ADM_{{ adhostname }} --stdin-password --domain={{ ad_domain_name }} --description="Admin group for {{ adhostname }} server" --domain-ou={{ srv_adm_grp_ou }} -U {{ username }}

    - name: Configuring sssd.conf
      template:
        src: ../templates/sssd.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: 0600

    - name: Configuring krb5.conf
      template:
        src: ../templates/krb5.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644

  - name: Configuring sudoers
    template:
      src: ../templates/adsudoers.j2
      dest: /etc/sudoers.d/adsudoers
      owner: root
      group: root
      mode: 0440

  - name: Configuring PAM/SSHD to use SSSD
    shell: authselect select sssd with-mkhomedir --force
    when: ansible_os_family == "RedHat"

  - name: Enabling oddjobd service
    systemd:
      name: oddjobd.service
      enabled: yes
      state: started

  - name: Restarting SSSD
    systemd:
      name: sssd
      enabled: yes
      state: restarted

# To run this playbook you need the ogratwicklcs.realmd_ipa_ad collection installed.  Instalation instructions below:
# ansible-galaxy collection install ogratwicklcs.realmd_ipa_ad
#
#    - name: Join host the Luc3.net Active Directory domain
#      ogratwicklcs.realmd_ipa_ad.realm_join:
#      realm_join:
#        domain: {{ ad_domain_name_alt }}
#        state: present
#        username: {{ username }}
#        password: {{ password }}