---
  - hosts: localhost
    vars:
        var_cohesity_restore_name: "NAS Test File Restore-nested-2"
        var_cohesity_job_name: "protect_nas"
        var_export_path: "chandu-ve-01-vip.pm.cohesity.com:/Insight-View01"
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Restore Files
        include_role:
            name: cohesity.cohesity_ansible_role
            tasks_from: restore_file
        vars:
            cohesity_server: "{{ var_cohesity_server }}"
            cohesity_admin: "{{ var_cohesity_username }}"
            cohesity_password: "{{ var_cohesity_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_restore_file:
                name: "{{ var_cohesity_restore_name }}"
                endpoint: "{{ var_export_path }}"
                state: present
                environment: "GenericNas"
                job_name: "{{ var_cohesity_job_name }}"
                files: 
                  - /demo/demo.json
                restore_location: /demo
                wait_for_job: yes
