---
  - hosts: localhost
    vars:
        var_export_path: chandu-ve-01-vip.pm.cohesity.com:/Insight-View01
    gather_facts: no
    roles:
        - cohesity.cohesity_ansible_role
    tasks:
      - name: Configure Cohesity Protection Source on NFS Export
        include_role:
            name: cohesity.cohesity_ansible_role
            tasks_from: source
        vars:
            cohesity_server: "{{ var_cohesity_server }}"
            cohesity_admin: "{{ var_cohesity_username }}"
            cohesity_password: "{{ var_cohesity_password }}"
            cohesity_validate_certs: "{{ var_validate_certs }}"
            cohesity_source:
                state: present
                endpoint: "{{ var_export_path }}"
                environment: "GenericNas"
                nas_protocol: "NFS"
        tags: [ 'cohesity', 'sources', 'register', 'nfs' ]